modLoader = "javafml" #mandatory
loaderVersion = "[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "All Rights Reserved"
[[mods]] #mandatory
modId = "shadowaddon" #mandatory
version = "1.18.2-1.3" #mandatory
displayName = "Shadow Addon" #mandatory
authors = "ycrns"
description = '''
An Addon mod for Create
'''
[[dependencies.shadowaddon]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[40,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.shadowaddon]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
[[dependencies.shadowaddon]]
modId="create"
mandatory=true
versionRange="[mc1.18.1_v0.4.1,)"
ordering="NONE"
side="BOTH"
